name: jinja_reflectable
description: Jinja reflectable.dart example.
version: 1.0.1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  jinja: ^0.4.0-0
  reflectable: ^3.0.0

dev_dependencies:
  build_runner: ^2.0.0
  lints: ^1.0.0

# dev.
#
# dependency_overrides:
#   jinja:
#     path: ../jinja